version: '3'
services:
  # zookeeper:
  #   image: zookeeper:latest
  #   ports:
  #     - "2181:2181"
  #     - "2888:2888"
  #     - "3888:3888"
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  # kafka-1:
  #   image: bitnami/kafka:latest
  #   ports:
  #     - "9092:9092"
  #     - "9094:9094"
  #   environment:
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,EXTERNAL://localhost:9094
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    # depends_on:
    #   - zookeeper
    # network_mode: "host"
  # kafka-2:
  #   image: bitnami/kafka:latest
  #   ports:
  #     - "9091:9092"
  #     - "9095:9094"
  #   environment:
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092,EXTERNAL://localhost:9094
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    # depends_on:
    #   - zookeeper
    # network_mode: "host"
  # kafka-ui:
  #   container_name: kafka-ui
  #   image: provectuslabs/kafka-ui:latest
  #   ports:
  #     - 9090:8080
  #   environment:
  #     - DYNAMIC_CONFIG_ENABLED='true'
  #     - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092,kafka-2:9092
  #     - KAFKA_CLUSTERS_0_NAME=kafka@local
  #   volumes:
  #     - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml
  #   depends_on:
  #     - kafka-1
  #     - kafka-2
  # conduktor:
  #   image: conduktor/conduktor-platform:latest
  #   ports:
  #     - "9080:8080"
  #   depends_on:
  #     - kafka-1
  #     - kafka-2
  # connect:
  #     image: debezium/connect
  #     ports:
  #       - "8083:8083"
  #     environment:
  #       - BOOTSTRAP_SERVERS=kafka-1:9092
  #       - GROUP_ID=1
  #       - CONFIG_STORAGE_TOPIC=topic-connect-connect-local
  #       - OFFSET_STORAGE_TOPIC=topic-connect-offset-connect-local
  #       - STATUS_STORAGE_TOPIC=topic-connect-status-local
  #     depends_on:
  #       - zookeeper
  #       - kafka-1
  #       - kafka-2
  # debezium-ui:
  #   image: debezium/debezium-ui:latest
  #   ports:
  #     - "7080:8080"
  #   environment:
  #     - KAFKA_CONNECT_URIS=http://connect:8083
  #   depends_on:
  #     - connect
  # ksqldb-server:
  #   image: confluentinc/ksqldb-server:latest
  #   hostname: ksqldb-server
  #   container_name: ksqldb-server
  #   depends_on:
  #     - kafka-2
  #   ports:
  #     - "8088:8088"
  #   environment:
  #     KSQL_LISTENERS: http://0.0.0.0:8088
  #     KSQL_BOOTSTRAP_SERVERS: kafka-2:9092
  #     KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
  #     KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
  # postgres-clean:
  #   image: postgres:latest
  #   hostname: postgres-clean
  #   container_name: postgres-clean
  #   ports:
  #     - "8765:5432"
  #   environment:
  #     - POSTGRES_PASSWORD=root
  # ksqldb-cli:
  #   image: confluentinc/ksqldb-cli:latest
  #   container_name: ksqldb-cli
  #   depends_on:
  #     - kafka-2
  #     - ksqldb-server
  #   entrypoint: /bin/sh
  #   tty: true
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
    command: 
      - "postgres"
      - "-c"
      - "max_wal_senders=4"
      - "-c"
      - "max_replication_slots=4"
      - "-c"
      - "wal_level=logical"
  notif:
    image: notif:latest
    ports:
      - "5001:5001"
      - "4000:4000"
    environment:
      - APP_ENV=staging
      - APP_HOST=
      - APP_PORT=5001
      - APP_NAME=efishery-service-notif
      - APP_SECRET=419vmKxA6KRbSeqcU4oGzwCPFTwxPIQp
      - APP_VERSION=1.0.0
      - LOAD_TEST=false
      - CLIENT_ID=e6970a9f-135f-4db1-9b7f-f9739bfe9fe6
      - STATIC_TOKEN=419vmKxA6KRbSeqcU4oGzwCPFTwxPIQp
      - JWT_SECRET=iE0G91yjtgP4eyX4xCwR3TCpnUmbZkcZ
      - POSTGRES_URL=postgres://postgres:YITt5zLLy4@postgres-service-notif--preprod.service.consul:7891/monorepo_notif_stg?sslmode=disable
      - OTEL_URL=https://eozk4iohtyuolhy.m.pipedream.net
      - OTEL_IS_SECURE=false
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_URL=rabbitmq
      - RABBITMQ_PORT=5672
      - ELASTIC_URL=elastic:9200
      - ELASTIC_INDEX=notif-logs-stg
      - ELASTIC_DOC_LIMIT=10000
      - REDIS_URL=redis:6379
      - REDIS_PORT=6379
      - JATIS_WA_USERNAME=StagingJTS2
      - JATIS_WA_PASSWORD=JtsStagingdua695%
      - JATIS_WA_URL=https://eozk4iohtyuolhy.m.pipedream.net
      - SERVICE_AUTH_URL=https://eozk4iohtyuolhy.m.pipedream.net
      - QONTAK_URL=https://eozk4iohtyuolhy.m.pipedream.net
      - QONTAK_CHANNEL_ID=99510530-b3c7-439b-8dee-8c41fdb1c2ec
      - QONTAK_TOKEN=jHjYQGYn_Lprf9OKxIU9IIXtdhCpxfhflSHYwScXBmY
      - QONTAK_USERNAME=sandbox11@qontak.com
      - QONTAK_PASSWORD=terbang123
      - QONTAK_CLIENT_ID=RRrn6uIxalR_QaHFlcKOqbjHMG63elEdPTair9B9YdY
      - QONTAK_CLIENT_SECRET=Sa8IGIh_HpVK1ZLAF0iFf7jU760osaUNV659pBIZR00
      - K1NG_API_KEY=IwiwqibGO8AcXGb
      - K1NG_API_PASSWORD=s87YZSvR
      - K1NG_URL=https://eozk4iohtyuolhy.m.pipedream.net
      - SMSVIRO_NOTIFY_URL=https://eozk4iohtyuolhy.m.pipedream.net
      - SMSVIRO_URL=https://eozk4iohtyuolhy.m.pipedream.net
      - SMSVIRO_API_KEY=863e130628e95ca166f9f9f36fd6c03b-74093160-2e0f-4da8-af46-7877187711af
      - JATIS_URL=https://eozk4iohtyuolhy.m.pipedream.net
      - JATIS_USERNAME=platformddm2m
      - JATIS_PASSWORD=platformddm2m123
      - JATIS_DIVISION=Platform Dan Data
      - INFOBIP_API_KEY=3da2cb90e2180421ad198c1cd969b7d2-f31eadb8-1899-4542-a95a-8b28a441bad7
      - INFOBIP_BASE=dp1zr.api.infobip.com
      - INFOBIP_USERNAME=eFishery_otp
      - INFOBIP_PASSWORD=eFishery2516!
      - INFOBIP_SENDER=EFISHERY
      - INFOBIP_NOTIFY_URL=https://eozk4iohtyuolhy.m.pipedream.net
    deploy:
      resources:
        limits:
          cpus: '0.128'
          memory: 256M
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - elastic
  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
  #   ports:
  #     - 1888:1888 # pprof extension
  #     - 8888:8888 # Prometheus metrics exposed by the collector
  #     - 8889:8889 # Prometheus exporter metrics
  #     - 13133:13133 # health_check extension
  #     - 4317:4317 # OTLP gRPC receiver
  #     - 4318:4318 # OTLP http receiver
  #     - 55679:55679 # zpages extension
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  elastic:
    image: elasticsearch:8.10.2
    ports:
      - "9200:9200"
      - "9300:9300"

    

