version: '3'
services:
  # rabbitmq:
  #   image: rabbitmq:3
  #   ports:
  #     - "15691:15691"
  #     - "15692:15692"
  #     - "25672:25672"
  #     - "4369:4369"
  #     - "5671:5671"
  #     - "5672:5672"
  rabbitmq-management:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
