version: '3'
services:
  elastic:
    image: elasticsearch:8.9.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.enabled=false
