version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml
    command: -config.file=/mnt/config/loki-config.yaml
  promtail:
    image: grafana/promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /Users/efishery/project/golang/efishery-service-commerce/local_log:/var/log
      - ./promtail/promtail.yaml:/etc/promtail/config.yml
    ports:
      - "9080:9080"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

volumes:
  prometheus-data:
